# Generated by Django 2.1.7 on 2019-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyid', models.IntegerField()),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('age', models.IntegerField(choices=[(1, '0 <= age < 0.5'), (2, '0.5 <= age < 1'), (3, '1 <= age < 1.5'), (4, '1.5 <= age < 2'), (5, '2 <= age < 3'), (6, '3 <= age < 4'), (7, '4 <= age < 5'), (8, '5 <= age < 6'), (9, '6 <= age < 7'), (10, '7 <= age < 8'), (11, '8 <= age < 9'), (11, '9 <= age < 10'), (12, '10 <= age < 11'), (13, '11 <= age < 12'), (14, '12 <= age < 13'), (15, '13 <= age < 14'), (16, '14 <= age < 15'), (17, '15 <= age < 16'), (18, '16 <= age < 17'), (19, '17 <= age < 18'), (20, '18 <= age < 19'), (21, '19 <= age < 65'), (22, '65 <= age')], default=1, verbose_name='age')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='sex')),
                ('women_s', models.IntegerField(choices=[(0, 'no'), (1, 'pregnancy first six month'), (2, 'pregnancy after six month'), (3, 'preg3'), (4, 'lact1'), (5, 'lact2')], default=0, verbose_name='women_special')),
                ('protein', models.FloatField(default=0, verbose_name='protein')),
                ('vita', models.FloatField(default=0, verbose_name='Vit-A')),
                ('fe', models.FloatField(default=0, verbose_name='iron')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'Family information',
                'verbose_name_plural': 'Family information',
            },
        ),
        migrations.CreateModel(
            name='FamilyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
    ]
