# Generated by Django 2.1.7 on 2019-02-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_family_familylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='women_s',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'pregnancy first 3 month'), (2, 'pregnancy 4 to 6 month'), (3, 'pregnancy 7 to 9 month'), (4, 'lactation 0-6 month'), (5, 'lactation over 7 month')], default=0, verbose_name='women_special'),
        ),
    ]
