# Generated by Django 2.1.7 on 2019-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190223_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='familyid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(default='no name', max_length=200, verbose_name='name'),
        ),
    ]
