# Generated by Django 2.1.3 on 2019-03-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190224_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyid', models.IntegerField(default=0)),
                ('food_item_id', models.IntegerField(default=1)),
                ('Food_name', models.CharField(max_length=200)),
                ('food_wt', models.FloatField(default=0, verbose_name='weight')),
                ('diet_type', models.IntegerField(default=1)),
            ],
        ),
    ]
