# Generated by Django 2.1.3 on 2019-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylist',
            name='fe_s',
            field=models.FloatField(default=0, verbose_name='iron'),
        ),
        migrations.AddField(
            model_name='familylist',
            name='protein_s',
            field=models.FloatField(default=0, verbose_name='protein'),
        ),
        migrations.AddField(
            model_name='familylist',
            name='vita_s',
            field=models.FloatField(default=0, verbose_name='Vit-A'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet_type',
            field=models.IntegerField(choices=[(1, 'conventional'), (2, 'recommended')], default=1),
        ),
        migrations.AlterField(
            model_name='familylist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
