# Generated by Django 2.1.3 on 2019-03-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190315_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='fe',
            field=models.FloatField(default=0, verbose_name='iron'),
        ),
        migrations.AddField(
            model_name='diet',
            name='protein',
            field=models.FloatField(default=0, verbose_name='protein'),
        ),
        migrations.AddField(
            model_name='diet',
            name='vita',
            field=models.FloatField(default=0, verbose_name='Vit-A'),
        ),
    ]
