# Generated by Django 2.1.3 on 2019-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190316_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familylist',
            name='fe_s',
            field=models.FloatField(default=0, verbose_name='iron_s'),
        ),
        migrations.AlterField(
            model_name='familylist',
            name='protein_s',
            field=models.FloatField(default=0, verbose_name='protein_s'),
        ),
        migrations.AlterField(
            model_name='familylist',
            name='vita_s',
            field=models.FloatField(default=0, verbose_name='Vit-A_s'),
        ),
    ]
