# Generated by Django 2.1.3 on 2019-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190316_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylist',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
