# Generated by Django 2.1.3 on 2019-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_familylist_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familylist',
            name='remark',
            field=models.CharField(blank=True, max_length=600, verbose_name='remark'),
        ),
    ]
